# Generated by Django 3.2.5 on 2022-01-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
